export const APPS = [
  {id:"dashboard", label:"Dashboard", icon:"bi-grid-1x2-fill", stage:1,
    items:[{key:"overview", label:"Overview", icon:"bi-speedometer2"}]},
  {id:"store", label:"Store", icon:"bi-shop-window", stage:1,
    items:[
      {key:"requests", label:"Store Requests", icon:"bi-clipboard-plus"},
      {key:"purchaserequests", label:"Purchase Requests", icon:"bi-cart-plus"},
      {key:"issues", label:"Store Issues", icon:"bi-box-arrow-up"},
      {key:"transfers", label:"Transfer Orders", icon:"bi-arrow-left-right"},
    ]},
  {id:"purchase", label:"Purchase", icon:"bi-cart3", stage:1,
    items:[
      {key:"rfq", label:"Requests for Quotation", icon:"bi-file-earmark-text", group:"Orders"},
      {key:"pos", label:"Purchase Orders", icon:"bi-file-earmark-check", group:"Orders"},
      {key:"requisitions", label:"Purchase Requests", icon:"bi-clipboard-check", group:"Orders"},
      {key:"requisitionlines", label:"Purchase Request Lines", icon:"bi-list-ul", group:"Orders"},
      {key:"grn", label:"Goods Receipts", icon:"bi-box-seam", group:"Orders"},
      {key:"invoices", label:"Vendor Invoices", icon:"bi-receipt", group:"Orders"},
      {key:"vendors", label:"Vendors", icon:"bi-truck", group:"Orders"},
      {key:"products", label:"Products", icon:"bi-tags", group:"Products"},
      {key:"reporting", label:"Purchase", icon:"bi-graph-up", group:"Reporting"},
      {key:"pricelists", label:"Vendor Pricelists", icon:"bi-currency-exchange", group:"Configuration"},
      {key:"reordering", label:"Reordering Rules", icon:"bi-arrow-repeat", group:"Configuration"},
      {key:"settings", label:"Settings", icon:"bi-gear", group:"Configuration"},
    ]},
  {id:"inventory", label:"Inventory", icon:"bi-boxes", stage:1,
    items:[
      {key:"overview", label:"Overview", icon:"bi-grid-1x2-fill"},
      {key:"stock", label:"Stock Levels", icon:"bi-bar-chart-line"},
      {key:"forecast", label:"Forecasted Report", icon:"bi-graph-up-arrow"},
      {key:"items", label:"Item Master", icon:"bi-tags"},
      {key:"transfers", label:"Transfers", icon:"bi-arrow-left-right"},
      {key:"adjustments", label:"Adjustments", icon:"bi-sliders"},
      {key:"scrap", label:"Scrap", icon:"bi-trash3"},
      {key:"warehouses", label:"Warehouses", icon:"bi-building"},
      {key:"reordering", label:"Reordering Rules", icon:"bi-arrow-repeat"},
    ]},
  {id:"manufacturing", label:"Manufacturing", icon:"bi-gear-wide-connected", stage:1,
    items:[
      {key:"orders", label:"Production Orders", icon:"bi-gear"},
      {key:"boms", label:"Bills of Materials", icon:"bi-diagram-3"},
      {key:"workcenters", label:"Work Centers", icon:"bi-cpu"},
      {key:"performance", label:"Performance", icon:"bi-speedometer2"},
    ]},
  {id:"quality", label:"Quality", icon:"bi-patch-check", stage:1,
    items:[
      {key:"inspections", label:"Inspections", icon:"bi-clipboard-data"},
      {key:"parameters", label:"QC Parameters", icon:"bi-list-check"},
    ]},
  {id:"sales", label:"Sales", icon:"bi-graph-up-arrow", stage:1,
    items:[
      {key:"orders", label:"Sales Orders", icon:"bi-cart-check"},
      {key:"shipments", label:"Shipments", icon:"bi-truck"},
      {key:"invoices", label:"Sales Invoices", icon:"bi-receipt-cutoff"},
      {key:"customers", label:"Customers", icon:"bi-people"},
    ]},
  {id:"accounting", label:"Accounting", icon:"bi-journal-bookmark", stage:1,
    items:[
      {key:"overview", label:"Overview", icon:"bi-calculator"},
      {key:"journal", label:"Journal Entries", icon:"bi-journal-text"},
      {key:"coa", label:"Chart of Accounts", icon:"bi-list-columns"},
      {key:"payable", label:"Payable", icon:"bi-cash-stack"},
      {key:"receivable", label:"Receivable", icon:"bi-cash"},
      {key:"tb", label:"Trial Balance", icon:"bi-clipboard-data"},
      {key:"is", label:"Income Statement", icon:"bi-graph-up"},
      {key:"bs", label:"Balance Sheet", icon:"bi-bar-chart-steps"},
    ]},
  {id:"pos", label:"Point of Sale", icon:"bi-shop", stage:2, items:[{key:"overview",label:"Overview",icon:"bi-speedometer2"}]},
  {id:"hr", label:"Employees", icon:"bi-person-badge", stage:2, items:[{key:"overview",label:"Overview",icon:"bi-speedometer2"}]},
  {id:"maintenance", label:"Maintenance", icon:"bi-tools", stage:2, items:[{key:"overview",label:"Overview",icon:"bi-speedometer2"}]},
  {id:"fleet", label:"Fleet", icon:"bi-truck-front", stage:3, items:[{key:"overview",label:"Overview",icon:"bi-speedometer2"}]},
  {id:"garage", label:"Repairs", icon:"bi-wrench-adjustable", stage:3, items:[{key:"overview",label:"Overview",icon:"bi-speedometer2"}]},
  {id:"contacts", label:"Contacts", icon:"bi-person-lines-fill", stage:3, items:[{key:"overview",label:"Overview",icon:"bi-speedometer2"}]},
  {id:"agents", label:"Agents", icon:"bi-person-workspace", stage:4, items:[{key:"overview",label:"Overview",icon:"bi-speedometer2"}]},
  {id:"approvals", label:"Approvals", icon:"bi-check2-square", stage:4, items:[{key:"overview",label:"Overview",icon:"bi-speedometer2"}]},
  {id:"reports", label:"Reporting", icon:"bi-graph-up-arrow", stage:4, items:[{key:"overview",label:"Overview",icon:"bi-speedometer2"}]},
  {id:"notifications", label:"Notifications", icon:"bi-bell", stage:4, items:[{key:"overview",label:"Overview",icon:"bi-speedometer2"}]},
  {id:"users", label:"Settings", icon:"bi-sliders2", stage:4, items:[{key:"overview",label:"Overview",icon:"bi-speedometer2"}]},
];

export const STAGE_PREVIEW = {
  pos: "Fast checkout on the same Item Master &amp; Customers as Sales — cart, walk-in customer, payment method, Complete Sale (already paid + already shipped at once), with Void restoring stock.",
  hr: "Employee records → monthly Payroll Run (Draft → Approved → Paid). Marking a run Paid posts gross salary expense, withholdings and net pay straight into Accounting.",
  maintenance: "Asset Register → Maintenance Request (Open → In Progress → Completed). Completing one consumes spare parts through the same stock ledger as everything else and posts Repairs &amp; Maintenance Expense.",
  fleet: "Vehicles (built on Maintenance's Asset Register) → Drivers → Trips/Dispatch Log with odometer readings → Fuel Logs posting Fuel Expense against Bank.",
  garage: "Mechanic roster → Repair Job (Open → In Progress → Completed), built on Maintenance's own Maintenance Request rather than a parallel system.",
  contacts: "One place rolling up every Customer's and Supplier's ledger — balance, history, aging — read from Sales/Purchase/Accounting rather than a second copy. Plus Balance Confirmations.",
  agents: "Field agents: validated stock receipt (In Transit → confirmed), agent sales invoices out of their own warehouse, collections with bank docs attached, and Finance-reviewed settlement.",
  approvals: "A configurable multi-step approval engine any module can route a document through — steps, owning role, and an optional value threshold.",
  reports: "A dashboard per module plus a generic reporting engine: date filters, totals, chart, CSV export and print for every report.",
  notifications: "A bell with unread count and inbox — approvals raise them automatically for whoever needs to act and whoever raised the request.",
  users: "Users &amp; Access Rights, VAT engine &amp; customer credit, pricing by destination, configurable document numbering, and Accounting Periods with posting-date control.",
};

export const STORAGE_KEY = "debora-food-complex-erp-v2";

export function seedState(){
  return {
    seq: 1,
    settings: { approvalThreshold: 5000 },
    reorderRules: [],
    accounts: [
      {code:"1000", name:"Bank", type:"asset"},
      {code:"1100", name:"Accounts Receivable", type:"asset"},
      {code:"1200", name:"Inventory Asset", type:"asset"},
      {code:"1300", name:"Goods Received Not Invoiced (GRNI)", type:"liability"},
      {code:"2000", name:"Accounts Payable", type:"liability"},
      {code:"3000", name:"Retained Earnings", type:"equity"},
      {code:"4000", name:"Sales Revenue", type:"revenue"},
      {code:"5000", name:"Cost of Goods Sold", type:"expense"},
      {code:"5100", name:"Inventory Adjustment Expense", type:"expense"},
      {code:"5200", name:"Store Issue / Department Consumption Expense", type:"expense"},
      {code:"5300", name:"Scrap / Inventory Loss Expense", type:"expense"},
      {code:"1400", name:"Manufacturing Labor & Overhead Clearing", type:"liability"},
    ],
    journal: [],
    departments: [
      {id:"dept-1", name:"Milling"},
      {id:"dept-2", name:"Packaging"},
      {id:"dept-3", name:"Quality Control"},
      {id:"dept-4", name:"Administration"},
      {id:"dept-5", name:"Fleet & Logistics"},
      {id:"dept-6", name:"Sales & Distribution"},
    ],
    storeRequests: [],
    storePurchaseRequests: [],
    storeIssues: [],
    suppliers: [
      {id:"sup-1", name:"Farmers Cooperative Union", category:"Local", certified:true},
      {id:"sup-2", name:"Oromia Grain Traders", category:"Local", certified:false},
    ],
    customers: [
      {id:"cus-1", name:"Merkato Retail Distributor"},
      {id:"cus-2", name:"Adama Wholesale Grocers"},
    ],
    warehouses: [
      {id:"wh-silo", name:"Grain Silo", stepsIncoming:1, stepsOutgoing:1, stepsManufacture:1},
      {id:"wh-pm",   name:"Packaging Store", stepsIncoming:1, stepsOutgoing:1, stepsManufacture:1},
      {id:"wh-wip",  name:"Milling Floor (WIP)", stepsIncoming:1, stepsOutgoing:1, stepsManufacture:1},
      {id:"wh-fg",   name:"Finished Goods Warehouse", stepsIncoming:1, stepsOutgoing:1, stepsManufacture:1},
      {id:"wh-byp",  name:"By-Product Store", stepsIncoming:1, stepsOutgoing:1, stepsManufacture:1},
      {id:"wh-qc",   name:"QC Hold", stepsIncoming:1, stepsOutgoing:1, stepsManufacture:1},
      {id:"loc-loss",name:"Inventory Loss (Scrap)", stepsIncoming:1, stepsOutgoing:1, stepsManufacture:1},
    ],
    items: [
      {id:"itm-maize", code:"RM-MAIZE-GRAIN", name:"Maize Grain (Bulk)", uom:"KG", type:"Raw Material", avgCost:35.00},
      {id:"itm-bag",   code:"PM-MADABERIYA-50KG", name:"Plastic Madaberiya 50kg Sack", uom:"PCS", type:"Packaging", avgCost:22.00},
      {id:"itm-duket", code:"FG-BEKKOLO-DUKET-50KG", name:"Bekkolo Duket (Maize Flour) 50kg", uom:"BAG", type:"Finished Good", avgCost:0},
      {id:"itm-bran",  code:"BY-MAIZE-BRAN", name:"Maize Bran (Gishaa)", uom:"KG", type:"By-Product", avgCost:0},
    ],
    requisitions: [],
    purchaseOrders: [],
    goodsReceipts: [],
    vendorInvoices: [],
    workCenters: [
      {id:"wc-mill", name:"Milling Line", hoursPerDay:8, hourlyRate:120},
      {id:"wc-pack", name:"Packing Bench", hoursPerDay:8, hourlyRate:60},
    ],
    boms: [{id:"bom-1", fgItemId:"itm-duket", lines:[{itemId:"itm-maize", qtyPerUnit:62.5},{itemId:"itm-bag", qtyPerUnit:1}],
      operations:[{id:"op-1", name:"Mill Grain", workCenterId:"wc-mill", durationMin:90},{id:"op-2", name:"Bag & Seal", workCenterId:"wc-pack", durationMin:30}]}],
    productionOrders: [],
    qcParameters: [
      {id:"qcp-1", name:"Moisture %", spec:"≤ 12.5%"},
      {id:"qcp-2", name:"Foreign matter %", spec:"≤ 1.0%"},
      {id:"qcp-3", name:"Off odor", spec:"None detected"},
    ],
    qcInspections: [],
    salesOrders: [],
    shipments: [],
    salesInvoices: [],
    ledger: [],
    transfers: [],
    adjustments: [],
    scrapOrders: [],
  };
}
